### ISSUE TITLE
Todos :+1:

### ISSUE THREAD

**Issue by Mvtthew** [MatiPati/cmnip-api#2]
``` /names ```
Returns all names ordered by name uses frequency 

``` /names?start=0&limit=5 ```
Returns first 5 names ordered by name uses frequency 

``` /names?year=2012 ```
Returns all names ordered by name uses frequency AND only from 2012 year

``` /names?year=2012&start=0&limit=5 ```
Returns first 5 names ordered by name uses frequency AND only from 2012 year

```  /name/{name} ```
Returns requested name per year statistics

``` /search/{name} ```
Returns names w/ statistics for all names matching q (search query)

**Comment by Nerio2** [comment]
all done ;)
